version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://deexitpatel4:4tadySqy0Perbe68@cluster0.lxc5xdx.mongodb.net/intervue?retryWrites=true&w=majority&appName=Cluster0
